### ISSUE TITLE
L - Highcharts Demo Radon

### ISSUE THREAD

**Issue by zuice32** [monksp/code4pa#10]

**Comment by GiGiCubed** [comment]
![chart (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59e7fa463b600500116fc621/125516c66e82c728ace21e0d46eb9c9b3196c3e1dea0fd0fe64de29b234324676b5ee17e2980b12cbc1a2a045a5c4bff10585e44fdf88b2ff4b56f62964e49bc8f3900299f7744eeaa880dbe08b0218e4f8cb4b8894bc0e83a25e099c2.png)

http://jsfiddle.net/p2wtfs3t/3/
